feat(launc hpage): initiall
zesty-io/nextjs-website pull request #1073
Opened 2022-09-21 16:42 UTC by darwin808

2022-09-22 12:24 UTC, ardeay requested changes
![image](https://user-images.githubusercontent.com/729972/191745718-42a230db-913f-4262-956f-838662050bd7.png)
Edit single page for marketplace items to check if its a type "template", if so, have the button open up "/launch/?template=ZUID"

2022-09-22 12:26 UTC, ardeay requested changes

2022-09-22 12:26 UTC, ardeay commented on src/pages/launch.js
> +  const handleDownload = async (e) => {
This functionality will belong in accounts under each instance

instances/ZUID/settings - add a card at bottom that says "export as template" which when the button is clicked, it creates a ZIP file

2022-09-22 15:27 UTC, darwin808 commented on src/pages/launch.js
> +  const handleDownload = async (e) => {
![image](https://user-images.githubusercontent.com/71545960/191788652-a4364a79-1347-494a-8440-cf2026abf9ac.png)

2022-09-22 15:34 UTC, darwin808 commented
@ardeay 

i perform a get request using the `meta.zuid` but i dont see the template zuid example `14-xxx` 

![image](https://user-images.githubusercontent.com/71545960/191790037-b50145d0-a7a0-46b2-98f9-6402a63fb02b.png)

2022-09-30 02:39 UTC, closed without merging

2022-09-30 02:40 UTC, darwin808 commented
please see for update https://github.com/zesty-io/website/pull/1085