Feat/site banner
zesty-io/nextjs-website pull request #1202
Opened 2022-10-18 16:35 UTC by jomarmontuya

2022-10-18 16:35 UTC, jomarmontuya commented
![image](https://user-images.githubusercontent.com/61284357/196490329-c43173a6-6da3-4ba1-a90a-e5e958a73d7e.png)

2022-10-18 18:14 UTC, ardeay requested changes
This need a dismiss button. That dismiss button will set a cookie, that cookie is checked before the banner loads and choses to show or not show the banner.

2022-10-20 12:48 UTC, jomarmontuya commented
![image](https://user-images.githubusercontent.com/61284357/196952685-180504ea-470e-48b1-b7fc-bc3399ca58d3.png)

![image](https://user-images.githubusercontent.com/61284357/196952922-65241e6f-07a8-454e-912c-17bd1a6f90b0.png)


Session cookie is set on banner dismissed

2022-10-20 13:14 UTC, darwin808 commented on src/components/marketing/SiteBanner/SiteBanner.js
> +              {bannerContent.data[0].content.banner_content ||
can we add a checker that bannerContent is Array to prevent error thanks

2022-10-20 13:54 UTC, jomarmontuya commented
Dev Branch Preview -> https://zesty-dev-website-m3rbwjxm5q-uc.a.run.app/

Dev branch is sync with current stage branch

2022-10-20 13:55 UTC, jomarmontuya commented
https://user-images.githubusercontent.com/61284357/196968475-d2798bad-66ee-436e-849a-6bb3ca3948f1.mp4

2022-10-20 14:32 UTC, darwin808 approved these changes

2022-10-26 17:03 UTC, merged