New/for developer page
zesty-io/nextjs-website pull request #1241
Opened 2022-10-26 14:06 UTC by jomarmontuya

2022-10-26 14:21 UTC, jeromeZestyIO reviewed
Please see the screenshot of the page - For Developers

![screencapture-localhost-3000-use-case-for-developers-2022-10-26-22_13_57](https://user-images.githubusercontent.com/115722439/198051468-df214eef-5200-4cb3-a703-3bdb7da17729.png)

2022-10-28 10:39 UTC, jeromeZestyIO reviewed
![screencapture-localhost-3000-use-case-for-developers-2022-10-28-02_32_55](https://user-images.githubusercontent.com/115722439/198568373-3e4c9095-c7b4-47e7-889b-994216463894.png)

2022-10-28 11:24 UTC, darwin808 commented on src/blocks/integrations/TechStack.js
> +  headerFontWeight,
we can have a default value `headerFontWeight`

2022-10-28 11:25 UTC, darwin808 commented on src/components/marketing/ForDeveloper/ContainerWithBackground.js
> +    <Box component="section">
try to use `Stack` if possible https://mui.com/material-ui/react-stack/

2022-10-28 11:28 UTC, darwin808 commented on src/components/marketing/ForDeveloper/Hero.js
> +            <Box
https://mui.com/material-ui/react-stack/ if possible use this

2022-10-28 11:30 UTC, darwin808 commented on src/components/marketing/ForDeveloper/Support.js
> +            p: isSmall ? 4 : 17,
you have 2 padding here

2022-10-28 11:33 UTC, darwin808 commented on src/components/marketing/ForDeveloper/ZestyDrives.js
> +          {data.map((e, i) => {
can we prevent error in data

2022-10-28 11:36 UTC, darwin808 requested changes
please resolve conflicts and also the commit message to prevent error in our ci 😊

2022-11-03 12:58 UTC, merged