Dev
zesty-io/nextjs-website pull request #1275
Opened 2022-11-02 12:15 UTC by darwin808

2022-11-02 15:02 UTC, ardeay requested changes

2022-11-02 15:02 UTC, ardeay commented on src/components/cta/DemoForm.js
> +// const getLeadObjectZOHO = (obj, roles) => {
Why are leads commented out?

2022-11-02 15:02 UTC, ardeay commented on src/components/cta/DemoForm.js
> +// const getLeadObjectZOHO = (obj, roles) => {
This object will need to come back

2022-11-02 15:02 UTC, ardeay commented on src/components/cta/TryFreeButton.js
> +// const mock = [
delete

2022-11-02 15:02 UTC, ardeay commented on src/components/docs/docsLookup.js
> +  // let markdownFilePathREADME = 'README.md';
bring back

2022-11-02 15:02 UTC, ardeay commented on src/components/wrappers/Page.js
>      AOS.refresh();
@darwin808 wasnt this removed with the bug?

2022-11-02 15:02 UTC, ardeay commented on src/lib/protectedRouteGetServerSideProps.js
> +import { getCookies } from 'cookies-next';
name space this  to `src/lib/accounts/protectedRouteGetServerSideProps.js`

2022-11-02 15:08 UTC, darwin808 commented on src/components/wrappers/Page.js
>      AOS.refresh();
![image](https://user-images.githubusercontent.com/71545960/199525906-ca08742d-e230-43f0-be30-3f027c872257.png)

@ardeay  this `AOS` is from an npm package and not from the cdn

2022-11-02 15:20 UTC, glespinosa commented
done updating request changes above

2022-11-03 12:48 UTC, ardeay commented
please make a separate PR from the branch into Stage @glespinosa

2022-11-03 13:30 UTC, closed without merging