Nav revamp
zesty-io/nextjs-website pull request #1415
Opened 2022-11-28 12:49 UTC by jomarmontuya

2022-11-28 12:52 UTC, jomarmontuya commented
https://user-images.githubusercontent.com/61284357/204282370-ec9e4e53-296b-4693-b101-f7f02255df17.mp4

2022-11-29 13:41 UTC, darwin808 requested changes

2022-11-29 13:41 UTC, darwin808 commented on src/pages/marketplace/index.js
> +  console.log(nav);
remove clg

2022-11-29 14:16 UTC, darwin808 submitted a review, later dismissed

2022-12-02 16:47 UTC, jomarmontuya commented
Holding off this navigation flyout till new pages are fully built out

2023-01-12 17:04 UTC, darwin808 requested changes
error when production = true 

![image](https://user-images.githubusercontent.com/71545960/212132394-1a7e87c9-e779-4557-9ba5-ef933c02816d.png)

No nav item in production =false testing local

2023-01-13 11:50 UTC, darwin808 approved these changes

2023-01-13 11:50 UTC, merged