Remove `packages` in package.json
zesty-io/nextjs-website pull request #1708
Opened 2023-05-04 13:57 UTC by darwin808

'@uiw/react-codemirror';
'@codemirror/view';
 '@codemirror/lang-javascript';
 '@uiw/codemirror-theme-github';

2023-05-04 16:28 UTC, giseleblair commented on src/pages/docs/parsley/tour/index.js
@darwin808 
only fetch production domains not webengine stage domains
` .get(
        'https://parsleydev-dev.webengine.zesty.io/-/instant/7-c005a8-zv6024.json',
      )`

2023-05-04 16:28 UTC, giseleblair commented on src/pages/docs/parsley/tour/index.js
why do we need to set algolia api keys here?

2023-05-04 17:18 UTC, darwin808 commented on src/pages/docs/parsley/tour/index.js
why do we need to set algolia api keys here?
- its for the algolia search bar

2023-05-04 21:34 UTC, ardeay requested changes
This PR comments out the problem areas. The problem areas commented out needs to be investigated. 

I upgraded the CPUs to 4 with always on CPU and 2GB more of ram. This should buy us time to solve the problem @darwin808 . If it does solve the problem it will be a temporary increase in resource until the problem is resolved. 

Please return the uncommented code and review the parsley functions for iteration leaks or timeout issues. Thank you

2023-05-05 06:35 UTC, darwin808 commented
> This PR comments out the problem areas. The problem areas commented out needs to be investigated.
> 
> I upgraded the CPUs to 4 with always on CPU and 2GB more of ram. This should buy us time to solve the problem @darwin808 . If it does solve the problem it will be a temporary increase in resource until the problem is resolved.
> 
> Please return the uncommented code and review the parsley functions for iteration leaks or timeout issues. Thank you

@ardeay can we merge this to `prod` for testing/monitoring and revert the cpu/memory to original then we can monitor it if the issue exist

also most error 504 is this pages 
![image](https://user-images.githubusercontent.com/71545960/236391006-7ef5a8e5-5353-4ec4-95b4-c9d700082b9f.png)

also saw our virtual size jump +8mb 
![image](https://user-images.githubusercontent.com/71545960/236391251-d629c49d-ae34-4423-b811-44e2ac3c9cf4.png)

2023-05-05 14:06 UTC, ardeay commented
The size of the container is not issues, it will be how the code is implemented to create a memory leak or a timeout. Let's meet

2023-05-05 14:16 UTC, ardeay commented
@darwin808 the issue is likely in new remote requests to get data something related to the parsley integration

2023-05-08 09:34 UTC, darwin808 commented
please see #1710

2023-05-08 09:34 UTC, closed without merging