Dev to Stage
zesty-io/nextjs-website pull request #1752
Opened 2023-05-22 10:55 UTC by glespinosa

- Created static layout components (https://docs.google.com/spreadsheets/d/1AYE9XnRVq8XRVOgd-G8g9yLqhDX4FuKkvdRU4EkQuJA/edit#gid=0)
- Component selector layouts
- resolved issue in navigation in mindshare not showing properly when user is logged in

2023-05-26 15:27 UTC, ardeay requested changes

2023-05-26 15:27 UTC, ardeay commented on src/revamp/ui/LightHero/index.js
> +  header = 'The future proof CMS for enterprise of any size',
This needs to be reverted to the original text

2023-05-26 15:27 UTC, ardeay commented on src/lib/ZestyView.js
> +  console.log(useAutoLayoutCheck());
remove console log

2023-05-29 11:44 UTC, glespinosa commented on src/lib/ZestyView.js
> +  console.log(useAutoLayoutCheck());
done

2023-05-29 11:44 UTC, glespinosa commented on src/revamp/ui/LightHero/index.js
> +  header = 'The future proof CMS for enterprise of any size',
done

2023-05-30 12:28 UTC, ardeay requested changes
Revert all language from that file. Update from latest stage

2023-05-30 12:28 UTC, ardeay commented on src/revamp/ui/LightHero/index.js
> +  subtitle = 'Create, distribute, and optimize content at SCALE with fewer resources in less time with the Zesty Hybrid Headless CMS. ',
This also needs to be reverted

2023-05-30 12:28 UTC, ardeay commented on src/revamp/ui/LightHero/index.js
> +  subtitle = 'Create, distribute, and optimize content at SCALE with fewer resources in less time with the Zesty Hybrid Headless CMS. ',
This whole file needs to be reverted, what has been changed is older language.

2023-05-30 12:49 UTC, glespinosa commented on src/revamp/ui/LightHero/index.js
> +  subtitle = 'Create, distribute, and optimize content at SCALE with fewer resources in less time with the Zesty Hybrid Headless CMS. ',
done

2023-05-30 13:58 UTC, ardeay approved these changes

2023-05-30 13:58 UTC, merged