Feat/support portal
zesty-io/nextjs-website pull request #2349
Opened 2024-02-06 07:54 UTC by japhethLG

# Description

Improved the UI and functionality of the ticket viewing section in the support portal. The updates include fixing the display of messages, images, and attachments, adding date and time displays for messages, ensuring only the agent's name is displayed per message, and enhancing attachment visibility for image and other file types.  Implemented a dark mode compatible UI, introduced an information bar on the right side, and refactored the code for fetching threads and attachments to improve the loading experience. A regex fix was added to handle threads without content.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Conducted manual testing by creating a ticket and using the Zoho portal to send and receive an email. This process was used to verify the correct display of messages, images, attachments, dates, and times, as well as the functionality of the new features.

- [x] Manual Test

# Screenshots / Screen recording

![Screenshot 2024-02-06 154906](https://github.com/zesty-io/website/assets/83058948/179be2ac-2efc-4c95-9229-19cdfd9281bd)
![Screenshot 2024-02-06 155009](https://github.com/zesty-io/website/assets/83058948/7b64b0c9-d51e-4c4f-b586-7efc4baf9e97)
![image viewer](https://github.com/zesty-io/website/assets/83058948/43e7a068-b1c9-4c78-bd3d-3fa3e3f957a9)
![dark mode](https://github.com/zesty-io/website/assets/83058948/8deb767b-6cab-4569-b30d-1a4ac6511a13)

2024-02-06 20:45 UTC, giseleblair commented on src/revamp/ui/GetDemoSection/index.js
why are there changes to these components?

2024-02-06 20:49 UTC, giseleblair requested changes
please review why there are edits to the GetDemoSection component, is it just prettier running its formatting or were there changes to the function?

2024-02-07 03:44 UTC, japhethLG commented on src/revamp/ui/GetDemoSection/index.js
I'm not sure why Jomar and Darwin's commit was mixed in here, will investigate this.

2024-02-07 04:15 UTC, japhethLG commented on src/revamp/ui/GetDemoSection/index.js
Found the issue, I rebased this branch to not include the unrelated commits.

2024-02-07 15:52 UTC, giseleblair commented
![Screenshot 2024-02-07 at 10 51 13 AM](https://github.com/zesty-io/website/assets/9896546/16604cfd-128c-430e-86c2-c170b9b06063)

@japhethLG can you please review the above message

2024-02-07 16:24 UTC, japhethLG commented
> ![Screenshot 2024-02-07 at 10 51 13 AM](https://private-user-images.githubusercontent.com/9896546/303045296-16604cfd-128c-430e-86c2-c170b9b06063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjMyMDcsIm5iZiI6MTcwNzMyMjkwNywicGF0aCI6Ii85ODk2NTQ2LzMwMzA0NTI5Ni0xNjYwNGNmZC0xMjhjLTQzMGUtODZjMi1jMTcwYjliMDYwNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMTYyMTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZjOTJlMWRlNWQ5MGJhMzA3MzAxNDNkY2ZjZGZhNzkwZDBiZTE1NDExMzNlNjk1ZjhhZTJlMTU3OTAwYzc3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lVY6fNA6_kHUGYPpYxz44uwywRfrithhOFO7BLFPWRU)
> 
> @japhethLG can you please review the above message

Merged stage to this branch.

2024-02-07 16:37 UTC, merged