Darwin1
zesty-io/nextjs-website pull request #372
Opened 2022-03-29 20:00 UTC by darwin808

Mostly css fixes for pages 

/ppc/digital-experience-platform/
/ppc/create-engaging-digital-experiences-at-scale/

please see commit message below

https://github.com/zesty-io/nextjs-website/issues/350

2022-03-29 23:17 UTC, ardeay commented
@darwin808 see change requests

2022-03-30 04:03 UTC, darwin808 commented
@ardeay can you send again the change request thanks

2022-03-30 13:00 UTC, ardeay requested changes

2022-03-30 16:16 UTC, ardeay approved these changes

2022-03-30 16:16 UTC, ardeay commented on src/blocks/heroes/HeroWithFormAndBackgroundGradient/HeroWithFormAndBackgroundGradient.js
> +  console.log(content, '2222');
remove this console log

2022-03-30 17:01 UTC, merged