added navigation to docs using mui accordion
zesty-io/nextjs-website pull request #540
Opened 2022-05-24 19:17 UTC by darwin808

added navigation to docs using mui accordion 
new library is installed

2022-05-24 19:23 UTC, darwin808 commented
![image](https://user-images.githubusercontent.com/71545960/170115985-d0991b33-76d0-4375-b4db-0c57214c6e90.png)
![image](https://user-images.githubusercontent.com/71545960/170116012-977d87c1-e8e1-4abf-b48c-a8dc7826fee3.png)

2022-05-25 02:03 UTC, ardeay requested changes

2022-05-25 02:03 UTC, ardeay commented on src/pages/docs/[...slug].js
> +            <AccordionMui header={jsonNav[0]} data={jsonNav[1]} />
@glespinosa please assist @darwin808 on this

2022-05-26 12:05 UTC, darwin808 commented
pictures
https://github.com/zesty-io/nextjs-website/issues/544

2022-05-26 13:31 UTC, merged