make install btn dynamic  in marketplace extension
zesty-io/nextjs-website pull request #548
Opened 2022-05-26 18:38 UTC by darwin808

2022-05-26 18:48 UTC, darwin808 commented
![image](https://user-images.githubusercontent.com/71545960/170556186-d9735b6d-6943-45a9-9269-e1a4e71515fa.png)
change theme of accordion

2022-05-27 13:14 UTC, ardeay requested changes
For custom styles, always instantiate the theme and use theme colors.

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/AccordionComp.js
> +  color: '#333333',
use zesty color, theme.pallete.zesty.grey or theme.palete.zesty.darkblue

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +  color: ${(props) => (props.active ? '#497edf' : '#333333')};
use Zesty colors from theme

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    color: #497edf;
zesty colors

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    background: #fafafa;
theme color paper level2

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    color: #497edf;
theme colors

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    color: #497edf;
theme colors

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +  background: #fff;
theme color background paper

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +  color: ${(props) => (props.active ? '#497edf' : '#333333')};
theme

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    color: #4973df;
theme

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    color: #497edf;
theme

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +  background: #fff;
theme

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    color: #497edf;
theme

2022-05-27 13:14 UTC, ardeay commented on src/components/Accordion/styles.js
> +    color: #497edf;
theme

2022-05-27 13:14 UTC, ardeay commented on src/views/marketplace/Extension.js
> +  if (data.app_zuid) {
make this chain of IF statement an if else, then you dont need extra clauses. There will only ever be one component to render

2022-05-27 14:52 UTC, ardeay approved these changes

2022-05-27 14:52 UTC, merged