Homepage Updates Feedback from katie
zesty-io/nextjs-website pull request #770
Opened 2022-08-09 13:40 UTC by jomarmontuya

2022-08-09 13:52 UTC, jomarmontuya commented
![screencapture-localhost-3000-2022-08-09-21_46_13](https://user-images.githubusercontent.com/61284357/183665482-2665f75f-2cc0-49f0-8354-52faf0a8cfc1.png)

2022-08-09 14:36 UTC, ardeay requested changes

2022-08-09 14:36 UTC, ardeay commented on src/views/zesty/Homepage.js
> +  console.log(content);
remove log

2022-08-09 16:21 UTC, jomarmontuya commented on src/views/zesty/Homepage.js
> +  console.log(content);
removed

2022-08-10 14:33 UTC, ardeay approved these changes

2022-08-10 14:33 UTC, merged