fix page crash if tags is missing | add check if the richtext editor …
zesty-io/nextjs-website pull request #800
Opened 2022-08-10 08:13 UTC by jomarmontuya

…is empty

2022-08-10 14:34 UTC, ardeay requested changes

2022-08-10 14:34 UTC, ardeay commented on src/views/zesty/Article.js
> +  console.log('simliarTags', simliarTags);
remove console log

2022-08-10 14:36 UTC, jomarmontuya commented on src/views/zesty/Article.js
> +  console.log('simliarTags', simliarTags);
Resolved

2022-08-10 14:45 UTC, jomarmontuya commented
sync stage

2022-08-11 14:35 UTC, ardeay approved these changes

2022-08-11 14:36 UTC, merged